#!/bin/bash

source ~bismark/etc/bdm_db.conf

# Lifted from http://stackoverflow.com/a/246128
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# This script is in $GOROOT/src/github.com/sburnett/bismark-tools/scripts, but
# the executable is in $GOROOT/bin/
EXE_PATH=$DIR/../../../../../bin/bdmq

PGHOST=$BDM_PG_HOST \
    PGPORT=$BDM_PG_PORT \
    PGDATABASE=$BDM_PG_MGMT_DBNAME \
    PGUSER=$BDM_PG_USER \
    PGPASSWORD=$BDM_PG_PASSWORD \
    PGSSLMODE=$BDM_PG_SSLMODE \
    $EXE_PATH $@
